#!/usr/bin/env bash
# setup.sh — first-time setup wizard for the tracing.run Docker deployment.
# Writes .env with required runtime config, then tells you to `docker compose up -d`.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

# Refuse to clobber an existing config
if [[ -f .env ]]; then
    echo "⚠ .env already exists. Refusing to overwrite."
    echo "  To re-run setup, delete it first:  rm .env"
    exit 1
fi

cat <<'BANNER'
─────────────────────────────────────────
 tracing.run — first-time setup
─────────────────────────────────────────
BANNER
echo

# ── Display name (optional, default Runner) ─────────────────────────────────
read -r -p "Display name (shown in app + used as container name) [Runner]: " name
name="${name:-Runner}"

# ── Login password (mandatory, strong, double-confirm) ──────────────────────
echo
echo "Login password — this is the ONLY auth gate. Make it strong."
while true; do
    read -r -s -p "  Password (≥12 chars): " pw1; echo
    read -r -s -p "  Confirm:             " pw2; echo
    if [[ -z "$pw1" ]]; then
        echo "    ✗ Password cannot be empty."
    elif [[ ${#pw1} -lt 12 ]]; then
        echo "    ✗ Must be at least 12 characters (got ${#pw1})."
    elif [[ "$pw1" != "$pw2" ]]; then
        echo "    ✗ Passwords do not match."
    else
        break
    fi
done

# ── LLM endpoint (optional — defaults work for local LiteLLM) ────────────────
echo
echo "LLM endpoint — leave blank to use the local LiteLLM defaults."
read -r -p "  Base URL [http://host.docker.internal:4000/v1]: " llm_url
llm_url="${llm_url:-http://host.docker.internal:4000/v1}"
read -r -p "  API key  [local-proxy]: " llm_key
llm_key="${llm_key:-local-proxy}"

# ── Write .env ──────────────────────────────────────────────────────────────
cat > .env <<EOF
# Generated by setup.sh on $(date -Iseconds)
DISPLAY_NAME=$name
LOGIN_PASSWORD=$pw1
LLM_BASE=$llm_url
LLM_API_KEY=$llm_key
EOF
chmod 600 .env

cat <<EOF

✓ Wrote .env (chmod 600 — readable only by you)

Next steps:
  1. Build + start the container
       docker compose up -d
  2. Open the app
       http://localhost:8507
  3. Log in with the password you just set
EOF
